import Head from 'next/head'
import {
    Box,
    Button,
    Chip,
    FormControl,
    Grid,
    InputAdornment,
    TextField,
    Typography,
} from "@mui/material"
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import CheckIcon from '@mui/icons-material/Check';
import { FormEvent, Key, useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { doDeposito, uploadResource } from '../api/api.service'
import Layout from '@/components/Layout'
import { useSession } from 'next-auth/react'
import { useCaixinhaSelect } from '@/hooks/useCaixinhaSelect';
import { toast } from 'react-toastify';
import CenteredCircularProgress from '@/components/CenteredCircularProgress';


export default function Deposito() {
    const { data, status } = useSession()
    const { caixinha } = useCaixinhaSelect()
    const router = useRouter()
    const [isLoading, setLoading] = useState(false)
    const [arquivos, setArquivo] = useState<any>([])
    const [solicitacao, setSolicitacao] = useState({
        valor: 0,
        fileUrl: '',
        memberName: "",
        email: '',
    })

    useEffect(() => {
        if (status === 'authenticated') {
            setSolicitacao({
                ...solicitacao,
                //@ts-ignore
                memberName: data['user']['name'],
                //@ts-ignore
                email: data['user']['email']
            })
        }
    }, [data, status])

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setSolicitacao({ ...solicitacao, [name]: value });
    }

    const request = useCallback((event: FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        setLoading(true)
        doDeposito({
            caixinhaId: caixinha?.id,
            name: solicitacao.memberName,
            email: solicitacao.email,
            valor: solicitacao.valor
        }).then(() => {
            router.push('/sucesso')
        }).catch(err => {
            console.log(err)
            setLoading(false)
            setTimeout(() => toast(err.message, { hideProgressBar: true, autoClose: 4000, type: 'error', position: 'bottom-right' }), 50)
        })
    }, [caixinha, solicitacao])

    const addComprovante = () => {
        let input = document.createElement('input');
        input.type = 'file';

        input.addEventListener('change', function (event: any) {
            let arquivo = event.target.files[0];

            console.log('Arquivo selecionado:', arquivo);
            setArquivo([...arquivos, { file: arquivo, name: arquivo.name }])

        });

        input.click()
    }

    const uploadItem = (resource: any) => {
        console.log(resource.name)

        uploadResource(resource.file).then((fileUrl: string) => {
            setTimeout(() => toast('upload realizado,', { hideProgressBar: true, autoClose: 4000, type: 'info', position: 'bottom-right' }), 50)
            //@ts-ignore
            const novaLista = arquivos.filter(it => it.name !== resource.name)
            novaLista.push({ file: resource, name: resource.name, status: 'success' })
            setArquivo(novaLista)
            setSolicitacao({ ...solicitacao, fileUrl })
        }).catch(() => alert('Ocorreu um problema ao enviar o arquivo'))
    }

    const getChipByItem = (item: any) => {
        if (item.status === 'success') {
            return (
                <Chip key={item.index} label={item?.name} onDelete={() => { alert('adicionado') }} deleteIcon={<CheckIcon />} />
            )
        }

        return (
            <Chip key={item.index} label={item?.name} variant="outlined" onDelete={() => { uploadItem(item) }} deleteIcon={<CloudUploadIcon />} />
        )
    }

    if (isLoading) return <CenteredCircularProgress />

    return (
        <Layout>
            <Head>
                <title>Caixinha</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box p={2}>
                    <Typography> Depositando em {caixinha?.name}</Typography>
                    <form onSubmit={request}>
                        <Grid container spacing={3}>
                            <Grid item xs={12}>
                                <FormControl fullWidth>
                                    <TextField
                                        required
                                        name="memberName"
                                        label="nome"
                                        disabled={true}
                                        value={solicitacao.memberName}
                                        defaultValue={solicitacao.memberName}
                                        onChange={handleChange}
                                        inputProps={{ "data-testid": "name" }}
                                    />
                                </FormControl>
                            </Grid>

                            <Grid item xs={12}>
                                <FormControl fullWidth>
                                    <TextField
                                        required
                                        name="email"
                                        label="email"
                                        type='email'
                                        value={solicitacao.email}
                                        defaultValue={solicitacao.email}
                                        onChange={handleChange}
                                        inputProps={{ "data-testid": "name" }}
                                    />
                                </FormControl>
                            </Grid>

                            <Box p={2}>

                                <TextField
                                    label="Valor depositado"
                                    id="outlined-start-adornment"
                                    defaultValue={solicitacao.valor}
                                    value={solicitacao.valor}
                                    onChange={handleChange}
                                    name='valor'
                                    type='number'
                                    sx={{ m: 1, width: '25ch' }}
                                    InputProps={{
                                        startAdornment: <InputAdornment position="start">R$</InputAdornment>,
                                    }}
                                />

                            </Box>

                            <Grid item xs={12}>
                                <Box display="flex" gap={2}>
                                    {arquivos.map((item: { name: string, index: Key }) =>
                                        getChipByItem(item)
                                    )}

                                </Box>
                                <Box display="flex" gap={2}>

                                    <Button
                                        onClick={addComprovante}
                                        variant="contained"
                                        color="secondary"
                                    >
                                        Adicionar Comprovante
                                    </Button>
                                </Box>
                            </Grid>

                            <Grid item xs={12}>
                                <Box display="flex" gap={2}>

                                    <Button
                                        type="submit"
                                        variant="contained"
                                        color="primary"
                                    >
                                        Enviar
                                    </Button>
                                </Box>
                            </Grid>
                        </Grid>
                    </form>
                </Box>
            </main>
        </Layout>
    )
}
