import Head from 'next/head'
import {
    Box,
    Button,
    FormControl,
    Grid,
    InputAdornment,
    List,
    ListItem,
    TextField,
    Typography,
} from "@mui/material"
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { doEmprestimo, getValorParcelas } from '../api/api.service'
import Layout from '@/components/Layout'
import { useSession } from 'next-auth/react'
import { toast } from 'react-toastify'
import { useCaixinhaSelect } from '@/hooks/useCaixinhaSelect'
import CenteredCircularProgress from '@/components/CenteredCircularProgress'

export default function Emprestimo() {
    const { data, status } = useSession()
    const router = useRouter()
    const { caixinha } = useCaixinhaSelect()
    const [isLoading, setLoading] = useState(false)
    const [solicitacao, setSolicitacao] = useState({
        valor: 0,
        juros: 2,
        parcela: 0,
        motivo: "",
        name: "",
        email: '',
    })
    const [stateParcelas, setStateParcelas] = useState({
        data: [],
        loading: false
    })

    useEffect(() => {
        if (status === 'authenticated') {
            setSolicitacao({
                ...solicitacao,
                //@ts-ignore
                name: data['user']['name'],
                //@ts-ignore
                email: data['user']['email']
            })
        }
    }, [data, status])

    useEffect(() => {
        if (!solicitacao.parcela) {
            return
        }
        setStateParcelas({
            data: [],
            loading: true
        })

        getValorParcelas({ parcelas: solicitacao.parcela, total: solicitacao.valor })
            .then(response => {
                setStateParcelas({
                    data: response,
                    loading: false
                })
            }).catch(() => {
                setStateParcelas({
                    data: [],
                    loading: false
                })
            })

    }, [solicitacao])

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setSolicitacao({ ...solicitacao, [name]: value });
    }

    const request = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        setLoading(true)
        doEmprestimo({ ...solicitacao, caixinhaID: caixinha?.id }).then(() => {
            router.push('/sucesso')
        }).catch(err => {
            console.log(err)
            setLoading(false)
            setTimeout(() => toast(err.message, { hideProgressBar: true, autoClose: 4000, type: 'error', position: 'bottom-right' }), 50)
        })
    }

    if (isLoading) return <CenteredCircularProgress />

    return (
        <Layout>
            <Head>
                <title>Caixinha</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box p={2}>
                    <Typography> Emprestimo em {caixinha?.name}</Typography>
                    <form onSubmit={request}>
                        <Grid container spacing={3}>
                            <Grid item xs={12}>
                                <FormControl fullWidth>
                                    <TextField
                                        required
                                        name="name"
                                        label="nome"
                                        disabled={true}
                                        value={solicitacao.name}
                                        defaultValue={solicitacao.name}
                                        onChange={handleChange}
                                        inputProps={{ "data-testid": "name" }}
                                    />
                                </FormControl>
                            </Grid>

                            <Grid item xs={12}>
                                <FormControl fullWidth>
                                    <TextField
                                        required
                                        name="email"
                                        label="email"
                                        type='email'
                                        value={solicitacao.email}
                                        defaultValue={solicitacao.email}
                                        onChange={handleChange}
                                        inputProps={{ "data-testid": "name" }}
                                    />
                                </FormControl>
                            </Grid>

                            <Grid item xs={12}>
                                <FormControl fullWidth>
                                    <TextField
                                        id="outlined-multiline-static"
                                        label="Motivo"
                                        name='motivo'
                                        multiline
                                        value={solicitacao.motivo}
                                        rows={4}
                                        defaultValue={solicitacao.motivo}
                                        onChange={handleChange}
                                    />
                                </FormControl>
                            </Grid>

                            <Box p={2}>

                                <TextField
                                    label="Valor solicitado"
                                    id="outlined-start-adornment"
                                    defaultValue={solicitacao.valor}
                                    value={solicitacao.valor}
                                    onChange={handleChange}
                                    name='valor'
                                    type='number'
                                    sx={{ m: 1, width: '25ch' }}
                                    InputProps={{
                                        startAdornment: <InputAdornment position="start">R$</InputAdornment>,
                                    }}
                                />
                                <TextField
                                    label="Juros a ser pago"
                                    id="outlined-start-adornment"
                                    onChange={handleChange}
                                    name='juros'
                                    type='number'
                                    value={solicitacao.juros}
                                    sx={{ m: 1, width: '25ch' }}
                                    defaultValue={solicitacao.juros}
                                    InputProps={{
                                        startAdornment: <InputAdornment position="start">%</InputAdornment>,
                                    }}
                                />
                                <TextField
                                    onChange={handleChange}
                                    name='parcela'
                                    type='number'
                                    value={solicitacao.parcela}
                                    label="Quantidade de parcelas"
                                    id="outlined-start-adornment"
                                    sx={{ m: 1, width: '25ch' }}
                                    defaultValue={solicitacao.parcela}
                                />

                            </Box>

                            <Grid item xs={12}>
                                <Box display="flex" gap={2}>

                                    <Button
                                        type="submit"
                                        variant="contained"
                                        color="primary"
                                    >
                                        Enviar
                                    </Button>

                                </Box>

                                {
                                    solicitacao.parcela >= 1 && (
                                        <>
                                            {
                                                stateParcelas.loading && <Typography>Calculando parcelamento</Typography>
                                            }
                                            {
                                                !stateParcelas.loading && (
                                                    <>
                                                        <Typography> Simulação do valor das parcelas (sem taxas e juros) </Typography>
                                                        <List>
                                                            {
                                                                stateParcelas.data.map((item: any, index) => (
                                                                    <ListItem key={index}>
                                                                        <Typography>R${item.value}</Typography>
                                                                    </ListItem>
                                                                ))
                                                            }
                                                        </List>
                                                    </>
                                                )
                                            }
                                        </>
                                    )
                                }
                            </Grid>
                        </Grid>
                    </form>
                </Box>
            </main>
        </Layout>
    )
}
